### ISSUE TITLE
editor panic appending empty line

### ISSUE THREAD

**Issue by lxl66566** [etienne-k/helix#30]
### Summary

```
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ropey-1.6.1/src/slice.rs:360:41:
called `Result::unwrap()` on an `Err` value: Char index out of bounds: char index 18446744073709551614, Rope/RopeSlice char length 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

hx
`x`  (to remove the first line)
`a`  (to append)

helix official has the better dealing: with the first line removed, press `aa` or `ii` to go to insert mode and recover the first line.

### Platform

Linux

### Terminal Emulator

konsole

### Installation Method

aur

### Helix Version

evil-helix 24.3 (d2a3d78b)

**Comment by lxl66566** [comment]
That might has been fixed in #23 ?

**Comment by lxl66566** [comment]
> That might has been fixed in #23 ?

no, i compiled the latest commit version (#db71fed2), and the panic still happens.

**Comment by usagi-flow** [comment]
Thank you for the report! I initially also wondered why #23 didn't fix this...

I'll see if I can prepare a few more changes so I can create a release this weekend.
